### PR TITLE
Integrate patches from Opensphere port

### PR DESCRIPTION
**Pull request by nyalldawson**
While we're collecting downstream patches, https://github.com/OPENSPHERE-Inc/o2/commits/master/ has a few useful ones

### CODE REVIEW

**Comment by m-kuhn** [comment]
> While we're collecting downstream patches, https://github.com/OPENSPHERE-Inc/o2/commits/master/ has a few useful ones

Interesting, how fo we feel about upstreaming there instead of forking?

**Comment by nyalldawson** [comment]
@m-kuhn 
https://github.com/qgis/o2/pull/1/commits/256c7f04f4bbe4119dcd477792e2d1b29be0781b will be a blocker for any full upstreaming of our patches. It's only semi complete, and I don't know what's involved in completing that.

Can we do our own for now and revisit later?

**Comment by m-kuhn** [comment]
If it's just that and we are happy with that upstream otherwise, we could also keep it as patch in the port.
@nyalldawson 

If there are good reasons to fork, I'm not opposed either

**Comment by nyalldawson** [comment]
Honestly, I'm just burnt out with my previous efforts to try and resurrect a maintained upstream by pushing qgis patches to a different fork (libdxfrw) and don't have the motivation to try again here. I'm happy if you want to try, but I just want to go the easy route 🙃

**Pull request merged**
