### PR TITLE
PKCE fixes

### PR DESCRIPTION
**Pull request by chenz-svsarrazin**
Fixes required to make PKCE work with Google.

### CODE REVIEW

**Comment by nyalldawson** [comment]
[8b4ec70](https://github.com/qgis/o2/pull/22/commits/8b4ec7026fef7def82b75665a03fb5327a740f27) is definitely required, that was accidentally omitted in the port from the QGIS code.

@elpaso what do you think about [ef0c16d](https://github.com/qgis/o2/pull/22/commits/ef0c16d3a3246d7fcbe0094cec8fc145da88db00)?

**Review by elpaso — APPROVED** [review]
Apparently, recommendations have changed since when PKCE was initially implemented and it is now recommended in addition to the code verifier also when client secret is used from confidential clients.

**Comment by nyalldawson** [comment]
Thanks @elpaso!

**Comment by chenz-svsarrazin** [comment]
Note also that `client_secret` is transmitted _unconditionally_ on the token refresh requests, which should follow the same rules wrt client authentication as the initial token request as far as I can tell from the RFC.

**Pull request merged**
